url: https://y7kim.github.io
baseurl: https://jishnurippon.github.io/securetea-web/
# for indivitual test use this url /agency-jekyll-theme/
# https://jishnurippon.github.io/securetea-web/

# Site settings
title: OWASP SecureTea
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


